on:
  pull_request:
    branches-ignore: []
  push:
    branches:
      - main


jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: gofmt
        run: |
          FORMAT_ERRORS=$(gofmt -s -l)
          if [[ -n "${FORMAT_ERRORS}" ]]; then
            echo "$FORMAT_ERRORS"
            exit 1
          fi
