name: Validate

on:
  pull_request:
    branches-ignore: []
  push:
    branches:
      - main


jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: gofmt
        run: |
          gofmt -s -l .
          test -z $(gofmt -s -l .)
